import type { Metadata } from "next";
import "./globals.css";
import {montserrat, santana, acumin} from "./components/fonts/fonts";

export const metadata: Metadata = {
  title: "Ontegra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${santana.variable} ${acumin.variable} ${montserrat.variable} font-santana`}>{children}</body>
    </html>
  );
}
